"""Add organizations and desks

Revision ID: 01115320d056
Revises: 2c5a6f8d1b20
Create Date: 2026-07-26 13:07:04.542013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01115320d056'
down_revision: Union[str, Sequence[str], None] = '2c5a6f8d1b20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_table('org_memberships',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('org_id', 'user_id')
    )
    op.create_table('desks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desks_id'), 'desks', ['id'], unique=False)
    op.create_index('ix_desks_room_id', 'desks', ['room_id'], unique=False)
    op.add_column('messages', sa.Column('desk_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'desks', ['desk_id'], ['id'], ondelete='CASCADE')
    op.add_column('rooms', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rooms', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'organization_id')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'desk_id')
    op.drop_index('ix_desks_room_id', table_name='desks')
    op.drop_index(op.f('ix_desks_id'), table_name='desks')
    op.drop_table('desks')
    op.drop_table('org_memberships')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
