"""add parent_id and edited_at to messages

Revision ID: 8f5fe7aa968a
Revises: b5eb2c27aba7
Create Date: 2026-08-04 23:10:03.748458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f5fe7aa968a'
down_revision: Union[str, Sequence[str], None] = 'b5eb2c27aba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('edited_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'messages', 'messages', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'edited_at')
    op.drop_column('messages', 'parent_id')
    # ### end Alembic commands ###
